insert into etiquettes (id, nom) values (1, 'Veggie');
insert into etiquettes (id, nom) values (2, 'Sucré');
insert into etiquettes (id, nom) values (3, 'Salé');
insert into etiquettes (id, nom) values (4, 'Végétarien');
insert into etiquettes (id, nom) values (5, 'Boeuf');
insert into etiquettes (id, nom) values (6, 'Poulet');
insert into etiquettes (id, nom) values (7, 'Poisson');
insert into etiquettes (id, nom) values (8, 'Sans crustacés');
insert into etiquettes (id, nom) values (9, 'Agneau');
insert into etiquettes (id, nom) values (10, 'Piquant');
insert into etiquettes (id, nom) values (11, 'Sans oeuf');
insert into etiquettes (id, nom) values (12, 'Chaud');
insert into etiquettes (id, nom) values (13, 'Froid');
insert into etiquettes (id, nom) values (14, 'Soft');
insert into etiquettes (id, nom) values (15, 'Alcool');
insert into etiquettes (id, nom) values (16, 'Sans lactose');
insert into etiquettes (id, nom) values (17, 'Sans gluten');
insert into etiquettes (id, nom) values (18, 'Trés piquant');
insert into etiquettes (id, nom) values (19, 'Français');
insert into etiquettes (id, nom) values (20, 'Sans noix');
insert into etiquettes (id, nom) values (21, 'Porc');